// import type { Metadata } from 'next';

import '../globals.css';
import React from 'react';

// export const metadata: Metadata = {
//   title: 'Rezy Admin Dashboard',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang='en'>
    //   <body className={inter.className}>{children}</body>
    // </html>
    <div>{children}</div>
  );
}
