import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import NavBar from '@/components/ui/Navbar';
import localFont from 'next/font/local';
import { getServerSession } from 'next-auth';
import NextAuthProvider from '@/components/providers/NextAuthProvider';

const gsans = localFont({
  src: [
    { path: '../fonts/GoogleSans-Regular.woff2', weight: '400' },
    { path: '../fonts/GoogleSans-Medium.woff2', weight: '500' },
    { path: '../fonts/GoogleSans-Bold.woff2', weight: '700' },
  ],
  variable: '--font-gsans',
});

export const metadata: Metadata = {
  title: 'Rezy Admin Dashboard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang='en' className={`${gsans.variable}`}>
      <body className={' font-gsans'}>
        <NextAuthProvider session={session}>
          {!!session && <NavBar />}
        </NextAuthProvider>
        {/* <NavBar /> */}
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
