name: "Lint"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  prettify-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: install node modules
        run: pnpm install
      - name: lint using ESLint
        run: pnpm run lint
